### PR TITLE
Update owncloud min-version

### PR DESCRIPTION
**Pull request by HanaGemela**
Fixes https://github.com/owncloud/customgroups/issues/306

### CODE REVIEW

**Comment by HanaGemela** [comment]
@phil-davis could you have a look at the failing CI?

**Comment by phil-davis** [comment]
@micbar I changed your commit so that in the `config[]` section it now selects different settings for the servers to run acceptance tests against.

The actual starlark code from `def main()` down is the same in all apps (almost - user_ldap has some bonus code). I really want to keep it like that, and drive everything by data in the `config[]` section. That makes it much easier when we find a bug in the starlark code - we can fix it and then just paste to all other apps without thinking too much.

**Comment by micbar** [comment]
@phil-davis Should we keep the tests runnning against daily master?

**Comment by phil-davis** [comment]
> @phil-davis Should we keep the tests runnning against daily master?

yes, we need to run acceptance tests with some core version

**Comment by micbar** [comment]
I meant we ran it against daily master and latest stable in the past, now we removed one platform. We could re enable it after the 10.4.0 release.

**Pull request merged**
