### PR TITLE
Register section for the app in settings

### PR DESCRIPTION
**Pull request by sharidas**
Register section for the app in settings

Signed-off-by: Sujith H <sharidasan@owncloud.com>

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks 👍

**Comment by PVince81** [comment]
@SergioBertolinSG why is it failing for mailhog here even though we don't care about email here ?

```
 [Behat\Testwork\Argument\Exception\UnknownParameterValueException]                                                

  Can not find a matching value for an argument `$mailhog_url` of the method `CustomGroupsContext::__construct()`.
```

**Comment by SergioBertolinSG** [comment]
Because tests here are directly affected by changes in core.

That variable is missing in the config.yml I can try to fix it.

**Comment by SergioBertolinSG** [comment]
Modified here https://github.com/owncloud/customgroups/pull/63 .

**Comment by PVince81** [comment]
@sharidas please rebase for CI

**Comment by PVince81** [comment]
then merge if it passes

**Comment by sharidas** [comment]
@PVince81 sure

**Pull request merged**
