### PR TITLE
Add custom icon

### PR DESCRIPTION
**Pull request by felixheidecke**
Fixes: https://github.com/owncloud/customgroups/issues/85

### CODE REVIEW

**Comment by felixheidecke** [comment]
Ah … I thought you merely meant this icon: 
bildschirmfoto 2017-09-06 um 17 33 24

The other icons needs a litte php magic.

**Comment by PVince81** [comment]
Apparently you can't simply get the request path in app.php:
```
± % occ app:enable customgroups

                                                                  
  [Exception]                                                     
  The requested uri() cannot be processed by the script './occ')  
                                                                  
```

a further hack would be to check the variable `\OC::$CLI` and skip the settings hack

**Comment by tomneedham** [comment]
> a further hack would be to check the variable \OC::$CLI and skip the settings hack

ahh damn, @mrow4a that means this also broke enabling the diagnostics app :( Need to check for \OC::$CLI as well.

**Comment by felixheidecke** [comment]
@PVince81 should I go the old fashioned way and add the icon to core?

**Comment by PVince81** [comment]
No, do the hacky way now to put a bit of pressure for https://github.com/owncloud/core/issues/28751 😉

**Comment by felixheidecke** [comment]
`php occ app:disable customgroups` works like a charm :-)

**Comment by PVince81** [comment]
```
Analysing /home/travis/build/owncloud/core/apps/customgroups/appinfo/app.php

 1 errors

    line   28: != - is discouraged

App is not compliant
```

Please use `!==`

**Pull request merged**
