### PR TITLE
Release 0.4.1

### PR DESCRIPTION
**Pull request by patrickjahns**

### CODE REVIEW

**Comment by patrickjahns** [comment]
Current conflict is with `.drone.yml` - will cherry-pick for the release

**Comment by patrickjahns** [comment]
@PVince81  - can you take a look at the makefile

**Comment by PVince81** [comment]
Makefile is fine, it's using yarn but our docker doesn't seem to have it.

I built final manually now and published it

**Comment by PVince81** [comment]
Closes https://github.com/owncloud/customgroups/issues/201

**Pull request merged**
