### PR TITLE
Change absolute notification URL to a relative one

### PR DESCRIPTION
**Pull request by JammingBen**
Related to https://github.com/owncloud/enterprise/issues/4250 as notifications URLs shouldn't be absolute to prevent problems with CORS.

### CODE REVIEW

**Comment by jvillafanez** [comment]
Could you double-check what happens if ownCloud is deployed in a path, such as `https://my.server.prv/owncloud`? I guess the notifications should start with `/owncloud/.....` but I'm not sure.

**Comment by JanAckermann** [comment]
@jvillafanez Works as designed
image

**Comment by jvillafanez** [comment]
We might need to touch the "notifications" app. Notifications sent via email might have a wrong link if the url isn't absolute (to be checked)
https://github.com/owncloud/notifications/blob/master/lib/Mailer/NotificationMailer.php#L73-L76

**Comment by JammingBen** [comment]
This PR handles the email sending: https://github.com/owncloud/notifications/pull/333

**Review by jvillafanez — APPROVED** [review]

**Pull request merged**
