### PR TITLE
Initialize DB with migration

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/customgroups/issues/10

### CODE REVIEW

**Comment by PVince81** [comment]
I'm stuck because am unable to create a unique index.
In MDB2 schema we had this:
```xml
<index>
    <name>cg_uri_index</name>
    <unique>true</unique>
    <field>
        <name>uri</name>
        <sorting>ascending</sorting>
    </field>
</index>
```

Now with Doctrine I define it as:
```php
    $table->addUniqueIndex(['uri'], 'cg_uri_index');
```

But MySQL is not happy:
```
± % sudo -uwwwrun ./occ app:enable customgroups
                              
  [Doctrine\DBAL\Exception\DriverException]                                                                                                                                                 
  An exception occurred while executing 'CREATE TABLE oc_custom_group (group_id INT UNSIGNED AUTO_INCREMENT NOT NULL, uri TINYTEXT NOT NULL, display_name TINYTEXT NOT NULL, UNIQUE INDEX   
  cg_uri_index (uri), PRIMARY KEY(group_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB':                                                                           
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'uri' used in key specification without a key length                                                             
                                                                                                                                                                                            

                                                                                                                                 
  [Doctrine\DBAL\Driver\PDOException]                                                                                            
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'uri' used in key specification without a key length  
                                                                                                                                 

                                                                                                                                 
  [PDOException]                                                                                                                 
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'uri' used in key specification without a key length  
```

This says that MySQL requires an explicit key length, basically how many of first characters of the field must be indexed: http://stackoverflow.com/a/1827118

However Doctrine doesn't allow you to pass a length for indices: https://github.com/doctrine/doctrine2/issues/3553 (won't fix as too DB specific)

I was told on IRC to try with varchar, let's find out how to do that...

**Comment by PVince81** [comment]
Note that in the MDB2 schema the "uri" column was specified as having the type "text" which is somehow mapped to "TINYTEXT"

**Comment by PVince81** [comment]
I changed the column type from "text" to "string" and now the index can be created properly.

It is now possible to enable this app and get the initial DB !

@DeepDiver1975 @VicDeo @jvillafanez please review

**Comment by PVince81** [comment]
btw, requires https://github.com/owncloud/core/pull/14851 checked out on master for it to work

**Comment by jvillafanez** [comment]
👍

**Pull request merged**
