### PR TITLE
Filter by scope

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/customgroups/issues/6

Requires https://github.com/owncloud/core/pull/27287

### CODE REVIEW

**Comment by jvillafanez** [comment]
👍 

Question: groups will be hidden if the scope isn't "sharing", do we want that?
* Show customs groups only for sharing  (current)
* Hide customs groups from management / user listing. Custom groups might be visible in other scopes.

I think this is fine, so no need to change anything.

**Comment by PVince81** [comment]
So far I didn't try to find all code paths that could pass a scope but didn't.

Regarding custom groups, we only ever want to show them for sharing, nowhere else. So if there's another "empty scope" case somewhere out there, we don't show them there.

More possible scopes that come to mind:
- autocomplete fields to disable apps for specific groups: let's exclude custom groups there
- autocomplete fields for admins to set external storage "applicable" field: let's exclude too
- autocomplete fields for "Exclude these groups from sharing": also exclude custom groups there
- more autocomplete fields related to sharing in the admin page: I'd also exclude custom groups from now.

Now if later we say we do want custom groups there, we could add a scope there later.

**Comment by jvillafanez** [comment]
This is more a whitelist vs blacklist topic. A whitelist makes more sense in this particular case.

If core enables more scopes, it's fine to add them in the whitelist later.

**Comment by PVince81** [comment]
Sounds good, whitelist it is then!

**Comment by PVince81** [comment]
Rebased to pick up the changes merged in core.

**Pull request merged**
