### PR TITLE
PHPUnit doesn't report all risky tests

### PR DESCRIPTION
**Pull request by PVince81**
@DeepDiver1975 see the two test classes `CustomGroupsBackendTest` and `CustomGroupsManagerTest`.

Each class has one empty test class.

When you run the tests with `make test-php` (or `cd tests/unit; phpunit`), it will only report one risky test:
```
1) OCA\CustomGroups\Tests\unit\CustomGroupsManagerTest::testEmpty
This test did not perform any assertions

/home/vincent/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:149
/home/vincent/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:100

OK, but incomplete, skipped, or risky tests!
Tests: 24, Assertions: 104, Risky: 1.
```

For some reason any risky tests inside of the first class alphabetically `CustomGroupsBackendTest` are ignored.

### CODE REVIEW

**Comment by PVince81** [comment]
(ignore the failing test, you can make it disappear by checking out the branch `group-displaynames` in core)

**Comment by PVince81** [comment]
Raised in core: https://github.com/owncloud/core/issues/26772

**Comment by DeepDiver1975** [comment]
> (ignore the failing test, you can make it disappear by checking out the branch group-displaynames in core)

set the branch name in travis.yml - https://github.com/owncloud/customgroups/pull/8/files#diff-354f30a63fb0907d4ad57269548329e3R9

**Comment by PVince81** [comment]
@DeepDiver1975 not needed, I'd rather have the core branch merged soon...

**Comment by PVince81** [comment]
Okay, I pushed the setting about empty tests to the app branch: https://github.com/owncloud/customgroups/pull/1

Thanks!

**Pull request closed without merging**
