### PR TITLE
add PHP7.2 to stable10

### PR DESCRIPTION
**Pull request by davitol**
add PHP7.2 to stable10

### CODE REVIEW

**Comment by PVince81** [comment]
Assigning self to fix the issue, looks non-trivial. Seems a method mock was missing.

**Comment by PVince81** [comment]
Weird. the tests ran locally for me

```
1) OCA\CustomGroups\Tests\unit\Dav\MembershipNodeTest::testDeleteSelfAsNonAdmin
Undefined index: user_id
/home/travis/build/owncloud/core/apps/customgroups/lib/Service/MembershipHelper.php:215
/home/travis/build/owncloud/core/apps/customgroups/lib/Dav/MembershipNode.php:124
/home/travis/build/owncloud/core/apps/customgroups/tests/unit/Dav/MembershipNodeTest.php:269
2) OCA\CustomGroups\Tests\unit\Dav\MembershipNodeTest::testDeleteAsSuperAdmin
Undefined index: user_id
/home/travis/build/owncloud/core/apps/customgroups/lib/Service/MembershipHelper.php:215
/home/travis/build/owncloud/core/apps/customgroups/lib/Dav/MembershipNode.php:124
/home/travis/build/owncloud/core/apps/customgroups/tests/unit/Dav/MembershipNodeTest.php:304
```

**Comment by PVince81** [comment]
Apparently I didn't rerun the tests before pushing... :-S

Fixed now.

**Comment by phil-davis** [comment]
Rebased to get CI fixes from #167

**Pull request merged**
